work_dir: ./work_dir/uav/ctrgcn_bone_motion_nowarmup
# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: ../resources/data/train_joint.npy
  label_path: ../resources/data/train_label.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 300
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: True
  bone: True

test_feeder_args:
  data_path: ../resources/data/val_joint.npy
  label_path: ../resources/data/val_label.npy
  window_size: 300
  p_interval: [0.95]
  vel: True
  bone: True
  debug: False
  normalization: False

# model
model: model.degcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  k: 8
  eta: 4
  num_stream: 2
  base_frame: 300
  graph: graph.uav_human.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
step: [35,60,75]
warm_up_epoch: 5
cosine_epoch: 60

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 80
nesterov: True