work_dir: ./work_dir/uav/ctrgcn_bone_v2
# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: ../resources/data/train_joint.npy
  label_path: ../resources/data/train_label.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: True
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: ../resources/data/test_joint_A.npy
  label_path: ../resources/data/test_label_A.npy
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False
  normalization: True

# model
model: model.ctrgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav_human.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 1e-5
min_lr: 1e-8
lr_decay_rate: 0.1
step: [10, 20]
warm_up_epoch: 0
optimizer: SGD

# training
device: [4,5]
batch_size: 128
test_batch_size: 128
num_epoch: 20
nesterov: True