work_dir: ./work_dir/uav/xsub1/agcn_joint
model_saved_name: ./runs/uav
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ../resources/data/train_bone.npy
  label_path: ../resources/data/train_label.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  random_rot: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../resources/data/val_bone.npy
  label_path: ../resources/data/val_label.npy

# model
model: model.tegcn.Model_two
model_args:
  num_class: 155
  num_point: 34
  num_person: 1
  graph: graph.uav_two.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0, 1 ,2, 3]
batch_size: 32
test_batch_size: 32
num_epoch: 60
nesterov: True
