work_dir: ./work_dir/uav/ctrgcn_joint_v2_debug
# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: ../resources/data/train_joint.npy
  label_path: ../resources/data/train_label.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: True
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: ../resources/data/val_joint.npy
  label_path: ../resources/data/val_label.npy
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False
  normalization: True

# model
model: model.ctrgcn.Model_two
model_args:
  num_class: 155
  num_point: 34
  num_person: 1
  graph: graph.uav_two.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
min_lr: 0.0001
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5
optimizer: SGD

# training
device: [0]
batch_size: 64
test_batch_size: 128
num_epoch: 65
nesterov: True